HTK_SRC     = HTK-3.4.1.zip
HTK_EXIST   = htk-3.4.1/bin.win32/HList.exe
HTK_WORKDIR = htk-3.4.1

all: htk

htk: $(HTK_SRC) $(HTK_EXIST)
	INSTALL.Cygwin.sh

$(HTK_EXIST):
	unzip $(HTK_SRC)
	mkdir -p htk-3.4.1/bin.win32

$(HTK_SRC):
	wget http://www.iir.nii.ac.jp/tmp/$(HTK_SRC)
